apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: cert
  files:
  - ca-cert.pem
  - ca-key.pem
- name: cabundle
  files:
  - cabundle