apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: admission-webhook

components:
- ../components/cert

replacements:
- source:
    kind: ConfigMap
    name: cabundle
    fieldPath: data.cabundle
  targets:
  - select:
      kind: ValidatingWebhookConfiguration
      name: validating-webhook-config.example.com
    fieldPaths:
    - webhooks.[name=validating-webhook-config.example.com].clientConfig.caBundle
  - select:
      kind: MutatingWebhookConfiguration
      name: mutating-webhook-config.example.com
    fieldPaths:
    - webhooks.[name=mutating-webhook-config.example.com].clientConfig.caBundle

resources:
- webhook-configuration.yaml